11 ДЗ
alspetrova/qa-automation-java pull request #11
Opened 2021-09-14 07:06 UTC by alspetrova

Добавила класс MapLoanCalcRepository (Map вместо массива)
Исправила методы по поиску и обновлению заявки
Добавлен метод getApplicationsByLoanType для поиcка по типу заявителя (ООО)
(задания со * не делала)

2021-09-15 16:41 UTC, andr92 requested changes

2021-09-15 16:41 UTC, andr92 commented on src/main/java/com/tinkoff/edu/app/model/LoanResponse.java
> +    public void setType(ResponseType type) {
лучше сначала описывать переменные, а после них методы. Так будет удобнее читать код

2021-09-15 16:41 UTC, andr92 commented on src/main/java/com/tinkoff/edu/app/repository/MapLoanCalcRepository.java
> +    private UUID requestId;*/
если лишний код - лучше убрать

2021-09-15 16:41 UTC, andr92 commented on src/test/java/com/tinkoff/edu/AppTest.java
> +        request = new LoanRequest(OOO, 12, 10_001,fio);
пропал пробел перед fio, alt+ctrl+L поправит

2021-09-15 16:41 UTC, andr92 commented on src/test/java/com/tinkoff/edu/AppTest.java
> +        assertTrue(responseList.size() > 0);
а что, если мы добавим в репо данные с другими типами, но наш метод поиска сломался и размер responeList будет все равно > 0, но с кучей ненужных данных? проверка при этом пройдет успешно

2021-09-15 16:43 UTC, andr92 commented on src/main/java/com/tinkoff/edu/app/repository/LoanCalcRepository.java
> +import java.util.List;
лишний импорт

2021-09-16 07:40 UTC, alspetrova commented on src/main/java/com/tinkoff/edu/app/model/LoanResponse.java
> +    public void setType(ResponseType type) {
исправила в след коммите

2021-09-16 07:40 UTC, alspetrova commented on src/main/java/com/tinkoff/edu/app/repository/LoanCalcRepository.java
> +import java.util.List;
исправила в след коммите

2021-09-16 07:40 UTC, alspetrova commented on src/main/java/com/tinkoff/edu/app/repository/MapLoanCalcRepository.java
> +    private UUID requestId;*/
исправила в след коммите

2021-09-16 07:40 UTC, alspetrova commented on src/test/java/com/tinkoff/edu/AppTest.java
> +        request = new LoanRequest(OOO, 12, 10_001,fio);
исправила в след коммите

2021-09-16 07:44 UTC, alspetrova commented on src/test/java/com/tinkoff/edu/AppTest.java
> +        assertTrue(responseList.size() > 0);
исправила в след коммите
и переделала на статику 
public static Map<UUID, LoanResponse> mapRepository = new HashMap<>();
потому что до этого создавался mapRepository для каждого теста
проверка пройдет успешно только для ООО (добавлен метод getApplicationsByLoanType(LoanType requester))
а как минимум 1 заявка от ООО будет, потому что ее создаем в тесте

2021-09-16 15:27 UTC, andr92 commented on src/test/java/com/tinkoff/edu/AppTest.java
> +        assertTrue(responseList.size() > 0);
разобрались в слаке

2021-09-16 16:02 UTC, merged